version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: preshoppy
      MYSQL_USER: preshoppy
      MYSQL_PASSWORD: preshoppy
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    volumes:
      - upload:/app/data/upload
    depends_on: 
      - db
    ports:
      - 3000:3000
    environment: 
      DB_HOST: db
      DB_NAME: preshoppy
      DB_USER: preshoppy
      DB_PASSWORD: preshoppy
volumes: 
  database:
  upload:
