version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: sure
      MYSQL_DATABASE: preshoppy
      MYSQL_USER: preshoppy
      MYSQL_PASSWORD: preshoppy
  web:
    image: node:14-alpine
    depends_on: 
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment: 
      DB_HOST: db
      DB_NAME: preshoppy
      DB_USER: preshoppy
      DB_PASSWORD: preshoppy
    working_dir: /usr/src/app
    command: npm run dev
